### ISSUE TITLE
Wren system timeline

### ISSUE THREAD

**Issue by lvivier** [wikihouseproject/Wren#1]
@claytonprest can you give any indication of when we might see the Wren system files in this repo? If there's anything I can do to help, I'm volunteering, though my CAD skills be rusty.

**Comment by claytonprest** [comment]
@lvivier Hi Luke, thanks for your offer of help! We're currently preparing the parametric Wren files for release, and road-testing it on a size-able pilot project in London. I expect within the next 2 months we'll have them hosted up on here. Initially these will be Rhino/Grasshopper (.ghx/.xml) format, but we are developing a parallel javascript code for the Wren system which will be much more accessible to developers.

In the meantime, the most up-to-date reference for Wren is the chassis model in the Microhouse repo, along with the accompanying assembly guide.

**Comment by lvivier** [comment]
Thanks for the quick response, @claytonprest. I'm excited to see the parametric files and especially the code. JavaScript is my day job so I can probably help out more when that comes to light. 

Not really pertinent to the issue, but is there a Slack or other chat channel where WikiHousers are connecting day to day?

**Comment by claytonprest** [comment]
@lvivier  Yes indeed - we have a Wikihouse community Slack. What's your email? I'll get an invite sent out to you.

**Comment by ghost** [comment]
hey, @claytonprest - would you be able to send me an invite also? it seems my old invite to slack is not working anymore. I'm running the Canadian chapter and need to keep up to date on what is happening. cleberfigueiredo at mac dot com

**Comment by lvivier** [comment]
@claytonprest I'm luke@vivier.ca
