### ISSUE TITLE
Compatibility with Mac

### ISSUE THREAD

**Issue by lingnand** [wikihouseproject/Wren#14]
Hi, 

First of all thanks for this wonderful project! (I'm into architecture and this seems to be the perfect opportunity to get involved)

I don't have much experience with Rhino (haven't really used it before actually), so bear with me if I'm asking beginner questions. I use Mac and tried out Rhino to run this project, but apparently the list of plugins required by Wren are not totally compatible with Mac Rhino.

### Things that succeeded

Human

### Things that failed

elefront

Is there any way to work around this problem? Or my best chance is to install Windows?

**Comment by pnprince** [comment]
Hi,

Sadly it doesn’t work with MAC OS. Back in April I have tried my best without any success. I ended up installing Windows 10 on External SSD with bootcamp on my MAC.

I would go with Windows. 

Cheers,

Piyush

**Comment by lingnand** [comment]
Thanks Piyush, I guess there's no other way then; I might still give Parallel Desktop a try just in case.

**Comment by pnprince** [comment]
One of the idea I had is to get rid of the dependacies and update the script such that It will work on MAC but requires little more work and anticipated.

**Comment by lingnand** [comment]
I think the main problem is probably elefront - do you want to upload the script to the repo and let me & others see if we can make it Mac-compliant?

Re elefront, I was hoping there is some way to contribute and make it Mac-compliant, but I didn't find a way (it seems to be developed by individuals behind the doors).
